// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbfTKDFHDBqKim4UTuOGpumCb4CSU2CE8',
    appId: '1:781738314572:web:68a58b84df512315a71de9',
    messagingSenderId: '781738314572',
    projectId: 'weather-application-df12c',
    authDomain: 'weather-application-df12c.firebaseapp.com',
    storageBucket: 'weather-application-df12c.appspot.com',
    measurementId: 'G-6LC3WWDK7D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ58I76NhmdWcXHCFywzkw97pQwniYHU8',
    appId: '1:781738314572:android:c497614da1304e6ea71de9',
    messagingSenderId: '781738314572',
    projectId: 'weather-application-df12c',
    storageBucket: 'weather-application-df12c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKpX6YWpshcuJ90EbOah68qOh3kPez67c',
    appId: '1:781738314572:ios:297816d888a3fb9da71de9',
    messagingSenderId: '781738314572',
    projectId: 'weather-application-df12c',
    storageBucket: 'weather-application-df12c.appspot.com',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKpX6YWpshcuJ90EbOah68qOh3kPez67c',
    appId: '1:781738314572:ios:297816d888a3fb9da71de9',
    messagingSenderId: '781738314572',
    projectId: 'weather-application-df12c',
    storageBucket: 'weather-application-df12c.appspot.com',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbfTKDFHDBqKim4UTuOGpumCb4CSU2CE8',
    appId: '1:781738314572:web:621b0afd851a2c88a71de9',
    messagingSenderId: '781738314572',
    projectId: 'weather-application-df12c',
    authDomain: 'weather-application-df12c.firebaseapp.com',
    storageBucket: 'weather-application-df12c.appspot.com',
    measurementId: 'G-J6H1M8EH9S',
  );

}